# Generated by Django 3.0.5 on 2020-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(max_length=2)),
                ('month', models.DateField()),
                ('description', models.CharField(max_length=80)),
                ('time', models.TimeField()),
            ],
        ),
    ]
