# Generated by Django 3.0.5 on 2020-05-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0003_remove_upcomingevents_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpcomingEvents',
            new_name='UpcomingEvent',
        ),
    ]
