# Generated by Django 3.0.5 on 2020-05-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0004_auto_20200506_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='location',
            field=models.CharField(default='41 okiki str grandmate', max_length=100),
        ),
    ]
