# Generated by Django 3.0.5 on 2020-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0009_latestsermon'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('For_What', models.CharField(default='church building', max_length=40)),
                ('brief_description', models.CharField(max_length=70)),
            ],
        ),
    ]
