# Generated by Django 3.0.5 on 2020-05-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0011_address_email_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone_number',
            old_name='phone_number',
            new_name='phone_numbers',
        ),
    ]
