# Generated by Django 3.0.5 on 2020-05-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0012_auto_20200507_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone_number',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
