# Generated by Django 3.0.5 on 2020-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0013_auto_20200507_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='phone_number',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
