# Generated by Django 3.0.5 on 2020-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0015_auto_20200507_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(default='defaultministry.jpg', upload_to='ministries_pic')),
            ],
        ),
    ]
