# Generated by Django 3.0.5 on 2020-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0016_ministries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(default='defaultdepart.jpg', upload_to='departments_pic')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.DeleteModel(
            name='ministries',
        ),
    ]
