# Generated by Django 3.0.5 on 2020-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0019_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsermon',
            name='audio',
            field=models.FileField(default='', upload_to='sermon_audio'),
        ),
    ]
