# Generated by Django 3.0.5 on 2020-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0021_auto_20200508_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsermon',
            name='audio',
            field=models.FileField(default='sermondefault.mp3', upload_to='sermon_audio'),
        ),
    ]
