# Generated by Django 3.0.5 on 2020-05-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0022_auto_20200508_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Ministries',
        ),
        migrations.AlterModelOptions(
            name='ministries',
            options={'verbose_name_plural': 'Ministries'},
        ),
        migrations.RenameField(
            model_name='ministries',
            old_name='department',
            new_name='Ministry',
        ),
    ]
