# Generated by Django 3.0.5 on 2020-05-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0024_auto_20200509_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
    ]
