# Generated by Django 3.0.5 on 2020-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0025_remove_video_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.TextField(default='enter text about the video', max_length=150),
        ),
    ]
