# Generated by Django 3.0.5 on 2020-05-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0027_customerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='address',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='full_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='state',
            field=models.CharField(default='enter state', max_length=150),
        ),
    ]
