# Generated by Django 3.0.5 on 2020-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0029_customerinfo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
