# Generated by Django 3.0.5 on 2020-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0031_auto_20200513_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsermon',
            name='image',
            field=models.ImageField(default='sermon.jpg', upload_to='sermons_pic'),
        ),
    ]
