# Generated by Django 3.0.5 on 2020-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0032_latestsermon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(default='donate.jpg', upload_to='donationproject_pic'),
        ),
    ]
