# Generated by Django 3.0.5 on 2020-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0033_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(default='donate.gif', upload_to='donationproject_pic'),
        ),
    ]
