# Generated by Django 3.0.5 on 2020-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0034_auto_20200513_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(default='donate.jpg', upload_to='donationproject_pic'),
        ),
    ]
