# Generated by Django 3.0.5 on 2020-05-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0036_auto_20200513_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
    ]
