# Generated by Django 3.0.5 on 2020-05-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0037_remove_video_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'verbose_name_plural': 'Donators'},
        ),
    ]
