# Generated by Django 3.0.5 on 2020-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0039_upcomingevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='prayerpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('prayers', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='latestsermon',
            name='audio',
        ),
    ]
