# Generated by Django 3.0.5 on 2020-05-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0040_auto_20200525_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prayerpoint',
            new_name='prayer',
        ),
    ]
