# Generated by Django 3.0.5 on 2020-05-25 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0041_auto_20200525_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayers',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
