# Generated by Django 3.0.5 on 2020-05-26 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0042_auto_20200525_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
