# Generated by Django 3.0.5 on 2020-05-26 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0043_prayer_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'verbose_name_plural': 'prayer points'},
        ),
        migrations.AlterField(
            model_name='latestsermon',
            name='word',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
