# Generated by Django 3.0.5 on 2020-05-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armyofjesuschrist', '0044_auto_20200526_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsermon',
            name='by',
            field=models.CharField(max_length=150),
        ),
    ]
